displayName: AnythingLLM Keycloak SSO
type: middleware
import: github.com/devantage/traefik-anythingllm-keycloak-sso
summary: Log in to AnythingLLM via OIDC on Keycloak
testData:
  keycloakIssuerURL: https://keycloak.example.com/realms/example
  keycloakClientId: clientId
  keycloakClientSecret: clientSecret
  anythingLLMBaseURL: https://anythingllm.example.com
  anythingLLMApiKey: apiKey
  sessionSecret: sessionSecret
